@startuml
start

: powerUp;
: setRandomMacAddress;
: connectToAccessPoint;
: setSleepMode;
note right
**modem** or **light** sleep mode
end note

while (true) is (true)
    : publishDummySensorData;
    note right
        Sends fake temperature 
        sensor data to a MQTT broker.
    end note
    : delay;
    note right
        for 15min
    end note
endwhile

end
@enduml