@startuml udp
start
: powerup;
: connect to Wifi;
while (for) is (i < 100)
    : start current measurement;
    : connect UDP to remote server;
    while (for) is (j < 10000)
        :sending;
        note right
            random input
        end note
    endwhile
    : disconnect UDP from remote server;
    : end current measurement;
    : wait 100 millisecondsendwhile;
endwhile
end
@enduml